### ISSUE TITLE
Report test results without showing stacktraces

### ISSUE THREAD

**Issue by renatoathaydes** [jeka-dev/jeka#197]
Currently, running `./jekaw java#test` when there are test failures results in the build printing out enormous amounts of stacktraces which are not very useful to the programmer trying to find out which tests passed and which didn't.

I would like to suggest that instead of printing all test output to stdout/stderr, Jeka should print a running status while tests are running, similar to cargo or npm, and finally print a short summary of how many tests ran, how many passed/failed, and maybe the list of failed tests... this requires that Jeka also generates reports, of course.

I am the author of [spock-reports](https://github.com/renatoathaydes/spock-reports) so as I have experience generating test reports, I could help with that if you would like it.

I would hate to add weight to Jeka, but I think test reports are important enough to be included by default (at least in the Java plugin), and I think it can be done in such a way that it's really very lightweight, given JUnit is already generating a XML report, so all that's left is converting that to a nice-for-humans HTML report, with a minimal amount of CSS to make it presentable.

**Comment by djeang** [comment]
Hi, sorry for the (very) late reply. I was focussing on writing a descent IntelliJ plugin and gave polish to the Jeka tool.

It has been improved a lot since the late release - and so includes test reports in jeka/output/test-report.
I am about to release version 0.10.0 but you can have a try now directly using the Intellij plugin with no install effort.

I'll be happy to get some feedbacks from you.
